# Generated by Django 4.1.7 on 2023-03-28 04:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0002_remove_comments_likes'),
        ('accounts', '0002_alter_account_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='liked_posts',
            field=models.ManyToManyField(related_name='user_likes', to='instagram.posts', verbose_name='Понравившиеся публикации'),
        ),
        migrations.AddField(
            model_name='account',
            name='subscriptions',
            field=models.ManyToManyField(related_name='subscription', to=settings.AUTH_USER_MODEL, verbose_name='Подписки'),
        ),
    ]
