# Generated by Django 4.1.7 on 2023-04-21 11:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0003_comments_created_at_posts_created_at'),
        ('accounts', '0003_account_liked_posts_account_subscriptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='liked_posts',
            field=models.ManyToManyField(blank=True, related_name='user_likes', to='instagram.posts', verbose_name='Понравившиеся публикации'),
        ),
        migrations.AlterField(
            model_name='account',
            name='subscriptions',
            field=models.ManyToManyField(blank=True, related_name='subscription', to=settings.AUTH_USER_MODEL, verbose_name='Подписки'),
        ),
    ]
